{
 "title": "LokiRuns",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loki Runs",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://storage.googleapis.com/thegym-public/thegym.jpg\"/>"
   }
  },
  {
   "title": "Latest Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "last_over_time ({app=\"lokiruns\"} | logfmt | line_format `{{.message}}` | json | line_format `{{.longitude}}` | unwrap longitude  [2s]) by (user)",
     "legendFormat": "longitude"
    },
    {
     "expr": "last_over_time ({app=\"lokiruns\"}| logfmt | line_format `{{.message}}` | json | line_format `{{.latitude}}` | unwrap latitude  [2s]) by (user)",
     "legendFormat": "latitude"
    }
   ]
  },
  {
   "title": "Heartrate (BPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time ({app=\"lokiruns\"} | logfmt | line_format `{{.message}}` | json | line_format `{{.heartrate}}` | unwrap heartrate [2s]) by (user)"
    }
   ]
  },
  {
   "title": "Pace (min/km)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time({app=\"lokiruns\"}  | logfmt | line_format `{{.message}}` | json | line_format `{{.speed}}` | unwrap speed [2s]) by (user)  * 16.66667"
    }
   ]
  },
  {
   "title": "Speed over Time (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time({app=\"lokiruns\"} | logfmt | line_format `{{.message}}` | json | line_format `{{.speed}}` | unwrap speed [2s]) by (user)  "
    }
   ]
  },
  {
   "title": "Last Heartrate (bpm)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time ({app=\"lokiruns\"} | logfmt | line_format `{{.message}}` | json | line_format `{{.heartrate}}` | unwrap heartrate  [2s]) by (user)"
    }
   ]
  }
 ]
}